# Generated by Django 5.2.8 on 2025-11-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add new book entries'), ('can_change_book', 'Can modify existing book entries'), ('can_delete_book', 'Can delete book entries')]},
        ),
    ]
